# Generated by Django 4.2.7 on 2023-11-17 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('impuestos', '0002_impuestos_delete_unidadmedida'),
        ('unidad_medida', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=240)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=240)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('codigo_barra', models.CharField(blank=True, max_length=250, null=True)),
                ('codigo_producto', models.CharField(blank=True, max_length=250, null=True)),
                ('lote', models.CharField(blank=True, max_length=250, null=True)),
                ('precio_costo', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('precio_mayorista', models.FloatField()),
                ('vencimiento', models.DateTimeField(blank=True, null=True)),
                ('estado', models.BooleanField(blank=True, default=True, null=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.clasificacion')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='impuestos.impuestos')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='productos.marca')),
                ('unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='unidad_medida.unidadmedida')),
            ],
        ),
    ]
