# Generated by Django 4.2.7 on 2023-11-18 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='existencia',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
