# Generated by Django 4.2.7 on 2023-11-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_productos_codigo_barra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='fecha_hora_registro',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
